
-- Create a table for fashion facts
CREATE TABLE public.fashion_facts (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  fact TEXT NOT NULL,
  category TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Insert 100 fashion facts
INSERT INTO public.fashion_facts (title, fact, category) VALUES 
('Moda Tarihi', 'İlk moda dergisi 1586''da Almanya''da yayınlandı ve sadece 16 sayfa içeriyordu.', 'history'),
('Renk Psikolojisi', 'Mavi renk güven ve profesyonellik hissi uyandırır, bu yüzden iş kıyafetlerinde sıkça tercih edilir.', 'color'),
('Kumaş Bilgisi', 'Pamuk, dünyanın en çok kullanılan doğal lifi olup, nefes alabilir ve dayanıklı özelliğiyle bilinir.', 'fabric'),
('Stil İpucu', 'Monokromatik kombinler (aynı rengin farklı tonları) şık ve uzun bir görünüm yaratır.', 'styling'),
('Moda Endüstrisi', 'Vintage kıyafetler çevre dostu moda seçenekleri arasında en popüler trendlerden biridir.', 'sustainability'),
('Aksesuar Kuralı', 'Klasik ''3''lü kural'': Aynı anda maksimum 3 aksesuar kullanmak en dengeli görünümü sağlar.', 'accessories'),
('Renk Uyumu', 'Renk çemberinde karşı karşıya olan renkler (mavi-turuncu) en güçlü kontrast kombinleri oluşturur.', 'color'),
('Kumaş Teknolojisi', 'Merino yünü, doğal antibakteriyel özelliği sayesinde koku yapmayan en popüler spor kumaşlarından biridir.', 'fabric'),
('Denim Tarihi', 'Jeans, 1873''te Levi Strauss tarafından altın madencileri için dayanıklı iş kıyafeti olarak icat edildi.', 'history'),
('Siyah Rengin Gücü', 'Siyah renk optik olarak 3-5 kilo zayıf gösterir ve evrensel şıklık sembolüdür.', 'color'),
('Chanel No.5', 'Dünyada en çok satılan parfüm Chanel No.5''tir ve her 30 saniyede bir şişe satılır.', 'luxury'),
('Yün Özellikleri', 'Yün, ağırlığının %30''una kadar su emebilir ve yine de kuru hissedilebilir.', 'fabric'),
('Stiletto Hikayesi', 'Stiletto topuklar, İtalyan hançer ''stiletto''dan ismini alır ve 1950''lerde popüler oldu.', 'shoes'),
('Beyaz Gömlek', 'Beyaz gömlek, gardırobun en çok yönlü parçasıdır - 15 farklı tarzda kombine edilebilir.', 'versatility'),
('Coco Chanel', 'Coco Chanel, kadınları korselerden kurtaran ve rahat giyimi moda haline getiren ilk tasarımcıdır.', 'designers'),
('İpek Üretimi', 'Bir ipek şalı yapmak için yaklaşık 1000 ipekböceği kozası gerekir.', 'fabric'),
('Kırmızı Ruj', 'Antik Mısır''da hem kadınlar hem erkekler dudaklarını kırmızıya boyardı.', 'makeup'),
('T-Shirt Tarihi', 'T-shirt, başlangıçta sadece iç çamaşırı olarak kullanılıyordu ve 1950''lerde dış giyim oldu.', 'history'),
('Altın Oran', 'Moda tasarımında ''altın oran'' (1:1.618) en estetik proporsiyon olarak kabul edilir.', 'design'),
('Kahverengi Kombinler', 'Kahverengi, doğanın rengi olduğu için neredeyse her renkle uyumludur.', 'color'),
('Vintage Tanımı', 'Vintage kıyafet, en az 20 yaşında olan ve dönemini temsil eden parçalardır.', 'vintage'),
('Kravat Tarihi', 'Kravat, 17. yüzyıl Hırvat askerlerinin boyun bağlarından gelir.', 'history'),
('Lacivert Özellikleri', 'Lacivert, siyahtan sonra en çok yönlü renktir ve %90 uyum sağlar.', 'color'),
('Keten Kumaş', 'Keten, 8000 yıldır kullanılan en eski dokuma kumaşlarından biridir.', 'fabric'),
('Ceket Düğmeleri', 'Erkek ceketlerinde sağ yakada düğme, kadın ceketlerinde sol yakada düğme olması Napolyon döneminden gelir.', 'tailoring'),
('Pembe Renk', 'Pembe, 18. yüzyılda erkeklerin rengi olarak kabul edilirdi.', 'color'),
('Moda Haftaları', 'Paris Moda Haftası, dünyanın en prestijli moda etkinliği olarak kabul edilir.', 'events'),
('Elastan Keşfi', 'Elastan (spandex), 1958''de DuPont tarafından icat edildi ve moda dünyasını değiştirdi.', 'fabric'),
('Asimetrik Tasarım', 'Asimetrik kesimler görsel ilgi yaratır ve vücudun farklı bölgelerini vurgular.', 'design'),
('Yünün Faydalari', 'Yün, doğal olarak kendi kendini temizler ve antimikrobiyal özelliklere sahiptir.', 'fabric'),
('Trend Döngüsü', 'Moda trendleri genellikle 20 yıllık döngülerle geri döner.', 'trends'),
('V Yaka Etkisi', 'V yaka, boynu uzun gösterir ve dekoltaj bölgesini ince çizer.', 'necklines'),
('Deri Bakımı', 'Kaliteli deri ürünler, doğru bakımla 20-30 yıl kullanılabilir.', 'leather'),
('Çizgi Etkisi', 'Dikey çizgiler boylu gösterir, yatay çizgiler genişlik illüzyonu yaratır.', 'patterns'),
('Moda İkonları', 'Audrey Hepburn, modern kadın tarzının en büyük etkilerinden biri olarak kabul edilir.', 'icons'),
('Tencel Kumaş', 'Tencel, okaliptüs ağacından yapılan çevre dostu bir kumaştır.', 'fabric'),
('Haute Couture', 'Haute Couture parçaları elle dikilir ve 100-1000 saat arasında sürebilir.', 'luxury'),
('Çanta Tarihi', 'İlk el çantaları 14. yüzyılda erkekler tarafından kullanılıyordu.', 'accessories'),
('Modal Kumaş', 'Modal, kayin ağacından elde edilen ipeksi yumuşaklıktaki kumaştır.', 'fabric'),
('Moda Terapisi', 'Bilimsel araştırmalara göre, güzel giyinmek kendine güveni %80 artırır.', 'psychology'),
('Düğme Tarihi', 'İlk düğmeler M.Ö. 2800''de süs amacıyla kullanılıyordu, fonksiyonel kullanım çok sonra başladı.', 'history'),
('Renk Görme', 'İnsan gözü yaklaşık 10 milyon farklı renk tonu algılayabilir.', 'color'),
('Kaşmir Elyafı', 'Kaşmir, keçi başına yılda sadece 150-200 gram elde edilen değerli bir elyaftır.', 'fabric'),
('Optik İllüzyon', 'Giyimde optik illüzyonlar vücut şeklini %30''a kadar farklı gösterebilir.', 'styling'),
('Moda Psikolojisi', 'Kırmızı giyen kişiler %25 daha özgüvenli algılanır.', 'psychology'),
('Polyester Keşfi', 'Polyester, 1941''de İngiltere''de icat edildi ve dayanıklılığıyla ünlüdür.', 'fabric'),
('Unisex Moda', 'Unisex giyim trendi 1960''ların sonunda başladı ve günümüzde yeniden popüler.', 'trends'),
('Nakış Sanatı', 'El nakışı, tekstilde en eski süsleme tekniklerinden biri olup 5000 yıllık geçmişe sahip.', 'craftsmanship'),
('Giyim Psikolojisi', 'Sarı renk yaratıcılığı ve mutluluğu artırdığı bilimsel olarak kanıtlanmış.', 'psychology'),
('Denim Yıkama', 'Raw denim, 6 ay giyildikten sonra ilk kez yıkanmalıdır.', 'care'),
('Kostüm Tarihi', 'İlk takım elbise 1666''da İngiltere''de Kral Charles II tarafından tanıtıldı.', 'history'),
('Gümüş Elyaf', 'Gümüş elyaf içeren kumaşlar, doğal antibakteriyel özelliğiyle kokusuz kalır.', 'technology'),
('Asimetrik Moda', 'Asimetrik kesimler 1960''larda Pierre Cardin tarafından popülerleştirildi.', 'design'),
('Doğal Boyalar', 'Organik boyalar kimyasal boyalardan %50 daha az çevre kirliliği yaratır.', 'sustainability'),
('Moda Dönemleri', 'Her moda dönemi genellikle 7-10 yıl sürer ve sonra evrim geçirir.', 'trends'),
('Alpaka Elyafı', 'Alpaka elyafı, kaşmirden daha yumuşak ve hipoalerjenik özelliğe sahiptir.', 'fabric'),
('Simetri Kuralı', 'İnsan beyni simetrik desenleri %60 daha çekici algılar.', 'psychology'),
('Moda Tasarımı', 'Bir moda koleksiyonu ortalama 6-12 ay önce tasarlanır.', 'design'),
('Renk Koordinasyonu', 'Analog renkler (yan yana renkler) en uyumlu kombinleri yaratır.', 'color'),
('Moda Sürdürülebilirliği', 'Fast fashion, moda endüstrisinin %20''sini oluştururken çevresel zararın %70''ini yaratır.', 'sustainability'),
('Geometric Desenler', 'Geometrik desenler modern tarzın temel taşlarından biridir.', 'patterns'),
('Moda Etiği', 'Etik moda hareketi 2000''li yılların başında başladı ve hızla büyüyor.', 'ethics'),
('Kumaş Ağırlığı', 'Kumaş ağırlığı metre kare başına gram ile ölçülür ve konfor belirler.', 'fabric'),
('Vintage vs Retro', 'Vintage orijinal dönem parçası, retro ise eski tarzı taklit eden yeni üretimdir.', 'vintage'),
('Moda Influencerları', 'İlk moda influencerı sayılan Brigitte Bardot 1950''lerde ün kazandı.', 'influence'),
('Mikro Fiber', 'Mikro fiber, insan saçından 100 kat daha incedir.', 'fabric'),
('Capsule Wardrobe', 'Capsule gardıroba, 30-40 parçayla sınırsız kombin yaratma konseptidir.', 'minimalism'),
('Moda Müzeleri', 'Metropolitan Sanat Müzesi''nin Kostüm Enstitüsü, dünyanın en büyük moda koleksiyonuna sahip.', 'culture'),
('Organik Pamuk', 'Organik pamuk üretimi %91 daha az su kullanır.', 'sustainability'),
('Moda Fotoğrafçılığı', 'İlk moda fotoğrafı 1856''da çekildi.', 'photography'),
('Renk Terapi', 'Yeşil renk göz yorgunluğunu azaltır ve rahatlatıcı etki yapar.', 'color'),
('Atelier Sistemi', 'Fransız atelier sistemi, moda eğitiminin temelini oluşturur.', 'education'),
('Smart Fabrics', 'Akıllı kumaşlar vücut ısısını algılayıp ona göre tepki verebilir.', 'technology'),
('Siluet Tarihi', 'A-line siluet, 1955''te Christian Dior tarafından yaratıldı.', 'silhouettes'),
('Tekstil Sanatı', 'Tekstil sanatı, insanlığın en eski sanat formlarından biridir.', 'art'),
('Renk Karışımı', 'Komplementer renkler karıştırıldığında gri tonu oluşur.', 'color'),
('Moda İllüstrasyonu', 'Moda illüstrasyonu, tasarım sürecinin %60''ını oluşturur.', 'illustration'),
('Ekolojik Ayak İzi', 'Bir pamuklu tişört üretmek için 2700 litre su gerekir.', 'sustainability'),
('Pattern Making', 'Kalıp yapımı, moda tasarımının en teknik kısmıdır.', 'technical'),
('Couture Tarihi', 'İlk couture evi 1858''de Charles Worth tarafından kuruldu.', 'history'),
('Renk Sembolizmi', 'Mor renk kraliyet ve lüksü simgeler, tarihte sadece seçkinler kullanabilirdi.', 'color'),
('Tekstil Baskı', 'İlk tekstil baskısı 2500 yıl önce Çin''de yapıldı.', 'printing'),
('Moda Eleştirisi', 'Moda eleştirisi, 19. yüzyılda bir meslek haline geldi.', 'criticism'),
('Sürdürülebilir Moda', 'Circular fashion modeli, %80 atık azaltımı sağlayabilir.', 'sustainability'),
('Moda Pazarlama', 'Influencer pazarlama, moda endüstrisinin %30''unu etkiliyor.', 'marketing'),
('Renk Etkisi', 'Turuncu renk enerji ve yaratıcılığı artırdığı bilimsel olarak kanıtlanmış.', 'psychology'),
('Moda Teknolojisi', '3D baskı teknolojisi moda tasarımını devrim niteliğinde değiştiriyor.', 'technology'),
('Vintage Değeri', 'Bazı vintage parçalar zamanla %500''e kadar değer kazanabilir.', 'investment'),
('Moda Sosyolojisi', 'Giyim, sosyal statünün en güçlü göstergelerinden biridir.', 'sociology'),
('Draping Tekniği', 'Draping, kumaşı manken üzerinde şekillendirme sanatıdır.', 'technique'),
('Moda Futurizmi', 'Geleceğin giysileri, iklim değişikliğine adapte olacak şekilde tasarlanıyor.', 'future'),
('Color Blocking', 'Color blocking tekniği 1960''larda Mondrian''ın eserlerinden ilham aldı.', 'technique'),
('Moda Antropolojisi', 'Giyim, kültürel kimliğin en önemli ifade araçlarından biridir.', 'anthropology'),
('Upcycling', 'Upcycling, eski kıyafetleri yeni tasarımlara dönüştürme sanatıdır.', 'sustainability'),
('Moda Arkeolojisi', 'En eski korunmuş giysi 5000 yıllık Tarkhan elbisesidir.', 'archaeology'),
('Bionic Fashion', 'Bionik moda, doğadan ilham alan tasarım yaklaşımıdır.', 'biomimicry'),
('Moda Algoritmaları', 'AI algoritmaları artık trend tahminlerinde %85 başarı oranına sahip.', 'ai'),
('Zero Waste', 'Zero waste tasarım, %100 kumaş kullanımını hedefler.', 'sustainability'),
('Moda Terapisi', 'Giyim terapi, psikolojik iyileşme sürecinde kullanılıyor.', 'therapy'),
('Quantum Dots', 'Quantum dot teknolojisi, renk değiştiren kumaşlar üretiyor.', 'nanotechnology'),
('Moda Blockchain', 'Blockchain teknolojisi moda endüstrisinde şeffaflık sağlıyor.', 'blockchain'),
('Biomimicry', 'Kelebek kanatlarından ilham alan kumaşlar iridescent efekt yaratıyor.', 'biomimicry'),
('Moda VR', 'Sanal gerçeklik, moda tasarım sürecini %40 hızlandırıyor.', 'vr'),
('Lab-grown', 'Laboratuvar ortamında üretilen deri, geleneksel deriye alternatif oluyor.', 'innovation');

-- Make the table publicly readable
ALTER TABLE public.fashion_facts ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Fashion facts are publicly readable" 
  ON public.fashion_facts 
  FOR SELECT 
  USING (true);
