// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsraqzofhnxkkgcwffuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzcmFxem9maG54a2tnY3dmZnVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzc2ODYsImV4cCI6MjA2NTkxMzY4Nn0._vGVmhYgAZHf1WuN5T1lFQVeNhfeIOUHUZ3EoauKQfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);